"""Rebuild Phase93 from the four official Round2 source files.

Required files beside this script:
  * Round2_Train_Channel.npy
  * Round2_Train_Pos.npy
  * Round2_Test_Pos.npy
  * Round2_Map.ply

No historical prediction array is an input. Every PAS/PDP descriptor,
official-like rectangular fold, OOF prediction, test prediction and final
Phase93 channel is generated by the stages below. Existing stage caches are
accepted so an interrupted multi-hour run can be resumed.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path

import numpy as np


ROOT = Path(__file__).resolve().parent
TEMP = Path(os.environ.get("TEMP", ROOT / "temp"))
RAW = (
    "Round2_Train_Channel.npy",
    "Round2_Train_Pos.npy",
    "Round2_Test_Pos.npy",
    "Round2_Map.ply",
)
FINAL_TEMP = TEMP / "Round2_Test_Channel_phase93_g56_antip10_plus_symmetric_clamp.npy"
FINAL_OUTPUT = ROOT / "Round2_Test_Channel_phase93_g56_antip10_plus_symmetric_clamp.npy"


@dataclass(frozen=True)
class Stage:
    name: str
    script: str
    args: tuple[str, ...] = ()
    env: dict[str, str] = field(default_factory=dict)


PHASE4_COMMON = {
    "R2_AFFINE_PROFILE": "1",
    "R2_QUADRATIC_PROFILE": "1",
    "R2_PROJECTION_ITERS_PROFILE": "1",
    "R2_FINAL_PAS_PROFILE": "1",
    "R2_PAS_LOW_RANK": "1",
    "R2_PAS_MOMENT_ALIGN": "1",
    "R2_SHADOW_CORRECTION_NOG7": "1",
    "R2_SHADOW_ITERATION_PROFILE_V3": "1",
    "R2_ROBUST_AMPLITUDE": "0.01",
    "R2_MATCHED_TARGET_SAFE": "1",
    "R2_MATCHED_PHASE_SAFE": "1",
    "R2_MATCHED_PHASE4": "1",
    "R2_PAS_POOL": "1",
    "R2_PAS_SMOOTH": "1",
    "R2_PDP_POOL": "1",
    "R2_PDP_SMOOTH": "1",
    "R2_PDP_POOL_GROUPS": "",
    "R2_MATCHED_JOINT_METRIC_KERNEL_G6": "1",
}


def stage_plan() -> list[Stage]:
    phase4_group10 = {
        **PHASE4_COMMON,
        "R2_BASE_PRED": "Round2_Test_Channel_matched_phase4_base.npy",
        "R2_GENERATE_ONLY_GROUP": "10",
    }
    phase10_env = {
        "R2_PHASE10_TARGET": "phase10_core125_complement100_primary_anchor_pas_band24_test.npy",
        "R2_PHASE10_VALIDATION": "phase10_core125_complement100_primary_anchor_confirmation.json",
        "R2_PHASE10_TARGET_MANIFEST": "phase10_core125_complement100_primary_anchor_manifest.json",
        "R2_PHASE10_OUTPUT": "Round2_Test_Channel_phase10_core125_complement100_anchor_pas.npy",
        "R2_PHASE10_MANIFEST": "phase10_core125_complement100_anchor_pas_submission_manifest.json",
    }
    return [
        Stage("map-los", "los_map_features.py"),
        Stage("map-local", "map_features.py"),
        Stage("map-rich", "build_rich_map_features.py"),
        Stage("channel-descriptors", "build_channel_descriptors.py"),
        Stage("rectangular-folds", "make_propagation_matched_splits.py"),
        Stage("matched-rank", "run_matched_rank_validation.py"),
        Stage("matched-candidate", "run_matched_candidate_validation.py"),
        Stage("metric-extended", "run_matched_metric_validation.py", env={"R2_METRIC_VALIDATION_MODE": "extended"}),
        Stage("metric-map", "run_matched_metric_validation.py", env={"R2_METRIC_VALIDATION_MODE": "map"}),
        Stage("metric-g6", "run_matched_metric_validation.py", env={"R2_METRIC_VALIDATION_MODE": "g6"}),
        Stage("joint-milestone", "summarize_matched_joint_milestone2.py"),
        Stage("phase1-oof", "run_matched_phase_validation.py"),
        Stage("phase2-oof", "run_matched_phase2_validation.py"),
        Stage(
            "phase3-refinements",
            "matched_target_refine_validation.py",
            env={
                "R2_REFINE_NAMES": ",".join(
                    (
                        "g1_affine_pas025_010_combo",
                        "g5_pas_smooth_hv010",
                        "g7_pdp_smooth_d5020",
                        "g10_affine_pas075_010",
                        "g10_refine10_lr0003",
                    )
                )
            },
        ),
        Stage("phase3-select", "matched_phase3_validation.py"),
        Stage("phase4-oof", "matched_phase4_composite_validation.py", env={"R2_SAVE_PHASE4_FOLDS": "1"}),
        Stage("phase4-base-test", "r2_pipeline.py", ("generate",), {**PHASE4_COMMON, "R2_OUTPUT": "Round2_Test_Channel_matched_phase4_base.npy"}),
        Stage("phase4-g10-affine", "r2_pipeline.py", ("generate",), {**phase4_group10, "R2_AFFINE_PAS_OVERRIDE": "0.75:0.10", "R2_OUTPUT": "Round2_Test_Channel_matched_phase4_g10_affine.npy"}),
        Stage("phase4-g10-gradient", "r2_pipeline.py", ("generate",), {**phase4_group10, "R2_REFINE_STEPS": "10", "R2_REFINE_LR": "0.003", "R2_OUTPUT": "Round2_Test_Channel_matched_phase4_g10_gradient.npy"}),
        Stage("phase4-test", "build_phase4_submission.py"),
        Stage("phase5-tree", "matched_phase5_tree_band_descriptor.py", env={"R2_BANDS": "24"}),
        Stage("phase5-rbf", "matched_phase5_rbf_band_descriptor.py", env={"R2_BANDS": "24"}),
        Stage("phase5-pdp", "matched_phase5_tree_pdp_ue_descriptor.py"),
        Stage("phase5-oof", "matched_phase5_composite_validation.py", env={"R2_BANDS": "24", "R2_SAVE_PHASE5_FOLDS": "1"}),
        Stage("phase5-test", "build_phase5_submission.py", env={"R2_BANDS": "24"}),
        Stage("phase6-mlp", "matched_phase6_pas_mlp_descriptor.py", env={"R2_BANDS": "24"}),
        Stage("phase6-canonical5", "matched_phase6_pas_canonical_descriptor.py", env={"R2_BANDS": "24", "R2_CANONICAL_SHIFT": "5.0", "R2_CANONICAL_COMPONENT": "1", "R2_CANONICAL_V_SHIFT": "0.0", "R2_CANONICAL_FRACTIONAL": "0"}),
        Stage("phase6-rich-tree", "matched_phase6_pas_rich_descriptor.py", env={"R2_BANDS": "24"}),
        Stage("phase6-rich-gate", "matched_phase6_pas_rich_gate.py", env={"R2_BANDS": "24"}),
        Stage("phase6-rich-mlp", "matched_phase6_pas_rich_mlp_descriptor.py", env={"R2_BANDS": "24"}),
        Stage("phase6-horizontal", "matched_phase6_pas_fitted_canonical.py", env={"R2_BANDS": "24"}),
        Stage("phase6-vertical", "matched_phase6_pas_fitted_vertical.py", env={"R2_BANDS": "24"}),
        Stage("phase6-safe", "matched_phase6_safe_combo_channel_validation.py", env={"R2_BANDS": "24"}),
        Stage("phase6-milestone", "matched_phase6_milestone_physics_validation.py", env={"R2_BANDS": "24"}),
        Stage("phase6-test", "build_phase6_submission.py", env={"R2_BANDS": "24"}),
        Stage("phase6-fold-channels", "matched_phase7_materialize_phase6_folds.py"),
        Stage("phase7-aggregate-audit", "matched_phase7_pas_aggregate_audit.py"),
        Stage("phase7-canonical", "matched_phase7_pas_aggregate_canonical.py"),
        Stage("phase7-harmonic", "matched_phase7_pas_aggregate_harmonic.py"),
        Stage("phase7-graph", "matched_phase7_pas_aggregate_graph_metric.py"),
        Stage("phase7-scale", "matched_phase7_pas_aggregate_scale_refine.py"),
        Stage("phase7-screen", "matched_phase7_pas_aggregate_portfolio_screen.py"),
        Stage("phase7-oof-calibration", "matched_phase7_pas_aggregate_oof_calibration.py"),
        Stage("phase7-local-gp", "matched_phase7_pas_aggregate_local_gp.py"),
        Stage("phase7-anchor", "matched_phase7_pas_aggregate_anchor_canonical.py"),
        Stage("phase7-cross-model", "matched_phase7_pas_aggregate_cross_model_portfolio.py"),
        Stage("phase7-global-selection", "matched_phase7_pas_aggregate_global_selection.py"),
        Stage("phase7-portfolio", "matched_phase7_pas_aggregate_portfolio_exact.py"),
        Stage("phase8-anchor-base", "phase8_anchor_retained_pas_screen.py"),
        Stage("phase8-anchor-gate", "phase8_anchor_local_gate_channel_validation.py"),
        Stage("phase9-pdp-folds", "phase9_buildable_full_pdp_screen.py"),
        Stage("phase9-oof", "phase9_buildable_joint_channel_validation.py"),
        Stage("phase9-test", "build_phase9_submission.py"),
        Stage("phase10-target", "phase10_pas_complement_anchor_confirmation.py"),
        Stage("phase10-channel", "build_phase10_robust125_anchor_pas_submission.py", env=phase10_env),
        Stage("phase40", "build_phase40_p9_actual_antip10_pas050_submission.py"),
        Stage("phase93", "build_phase93_g56_antip10_plus_symmetric_clamp_submission.py"),
    ]


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        while block := stream.read(8 * 1024 * 1024):
            digest.update(block)
    return digest.hexdigest()


def verify_raw() -> dict[str, object]:
    missing = [name for name in RAW if not (ROOT / name).exists()]
    if missing:
        raise FileNotFoundError(
            "Place the four official source files beside this script: "
            + ", ".join(missing)
        )
    train_pos = np.load(ROOT / "Round2_Train_Pos.npy", mmap_mode="r")
    test_pos = np.load(ROOT / "Round2_Test_Pos.npy", mmap_mode="r")
    channel = np.load(ROOT / "Round2_Train_Channel.npy", mmap_mode="r")
    expected_channel = (4000, 256, 4, 192)
    if train_pos.shape[0] != 4000 or test_pos.shape[0] != 500:
        raise ValueError(
            f"unexpected positions: train={train_pos.shape}, test={test_pos.shape}"
        )
    if channel.shape != expected_channel or channel.dtype != np.complex64:
        raise ValueError(
            f"unexpected training channel: {channel.shape} {channel.dtype}; "
            f"expected {expected_channel} complex64"
        )
    return {
        "train_pos_shape": list(train_pos.shape),
        "test_pos_shape": list(test_pos.shape),
        "train_channel_shape": list(channel.shape),
        "train_channel_dtype": str(channel.dtype),
    }


def run_stage(stage: Stage, index: int, total: int) -> None:
    script = ROOT / stage.script
    if not script.exists():
        raise FileNotFoundError(f"stage source missing: {script}")
    env = os.environ.copy()
    env.update(stage.env)
    print(
        json.dumps(
            {
                "event": "stage_start",
                "index": index,
                "total": total,
                "name": stage.name,
                "script": stage.script,
            }
        ),
        flush=True,
    )
    subprocess.run(
        [sys.executable, str(script), *stage.args],
        cwd=ROOT,
        env=env,
        check=True,
    )
    print(json.dumps({"event": "stage_complete", "name": stage.name}), flush=True)


def validate_final() -> dict[str, object]:
    if not FINAL_TEMP.exists():
        raise FileNotFoundError(f"Phase93 builder did not create {FINAL_TEMP}")
    value = np.load(FINAL_TEMP, mmap_mode="r")
    finite = True
    nonzero = True
    for start in range(0, len(value), 8):
        block = np.asarray(value[start : start + 8])
        finite &= bool(np.isfinite(block).all())
        nonzero &= bool(np.all(np.sum(np.abs(block), axis=(1, 2, 3)) > 0))
    if value.shape != (500, 256, 4, 192) or value.dtype != np.complex64:
        raise ValueError(f"unexpected final output: {value.shape} {value.dtype}")
    if not finite or not nonzero:
        raise ValueError("final output contains non-finite or all-zero rows")
    source_hash = sha256(FINAL_TEMP)
    if FINAL_OUTPUT.exists() and sha256(FINAL_OUTPUT) != source_hash:
        raise FileExistsError(
            f"refusing to overwrite different final output: {FINAL_OUTPUT}"
        )
    if not FINAL_OUTPUT.exists():
        shutil.copy2(FINAL_TEMP, FINAL_OUTPUT)
    return {
        "path": FINAL_OUTPUT.name,
        "shape": list(value.shape),
        "dtype": str(value.dtype),
        "bytes": FINAL_OUTPUT.stat().st_size,
        "sha256": source_hash,
        "finite": finite,
        "all_rows_nonzero": nonzero,
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--from-stage",
        help="resume at the named stage; earlier cached stages are not invoked",
    )
    parser.add_argument("--list-stages", action="store_true")
    args = parser.parse_args()
    stages = stage_plan()
    if args.list_stages:
        for index, stage in enumerate(stages, 1):
            print(f"{index:02d} {stage.name}: {stage.script}")
        return
    raw_summary = verify_raw()
    start = 0
    if args.from_stage:
        names = [stage.name for stage in stages]
        if args.from_stage not in names:
            raise ValueError(f"unknown stage {args.from_stage!r}; use --list-stages")
        start = names.index(args.from_stage)
    print(json.dumps({"event": "raw_verified", **raw_summary}), flush=True)
    for index, stage in enumerate(stages[start:], start + 1):
        run_stage(stage, index, len(stages))
    manifest = {
        "pipeline": "official raw data -> rectangular OOF training -> Phase4 -> Phase5 -> Phase6 -> P9 -> Phase10 -> Phase40 -> Phase93",
        "raw_inputs": list(RAW),
        "historical_prediction_inputs": [],
        "stage_count": len(stages),
        "final": validate_final(),
    }
    (ROOT / "phase93_raw_end_to_end_manifest.json").write_text(
        json.dumps(manifest, indent=2), encoding="utf-8"
    )
    print(json.dumps({"event": "complete", **manifest["final"]}), flush=True)


if __name__ == "__main__":
    main()
